-- 2022년 4월 13일 취소되지 않은 흉부외과(CS) 진료 예약 내역 조회
-- 진료예약번호, 환자이름, 환자번호, 진료과코드, 의사이름, 진료예약일시 항목
-- 진료예약일시 오름차순

# SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
# FROM APPOINTMENT A, PATIENT P, DOCTOR D
# WHERE A.PT_NO = P.PT_NO AND A.MDDR_ID = D.DR_ID AND DATE_FORMAT(A.APNT_YMD, '%Y-%m-%d') = '2022-04-13' AND A.APNT_CNCL_YN = 'N' AND A.MCDP_CD = 'CS'
# ORDER BY A.APNT_YMD;

-- 2022년 4월 13일 cs 진료예약
SELECT R.APNT_NO, P.PT_NAME, R.PT_NO, R.MCDP_CD, D.DR_NAME, R.APNT_YMD
FROM (
    SELECT *
    FROM APPOINTMENT
    WHERE MCDP_CD = 'CS' AND DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13' AND APNT_CNCL_YN = 'N'
    ) R, DOCTOR D, PATIENT P
WHERE R.PT_NO = P.PT_NO AND R.MDDR_ID = D.DR_ID
ORDER BY 6;